source configure.sh
ENCODING=$1
PEPTIDE_TYPE=$2
FEATURE_TYPE=$3
NORMALIZER="${4:-q}"
ALPHA="${5:-0.005}"
WORK_DIR="${6:-/home/localadmin/Priorization/Classifiers/}"
CLF_BIN_WC1=$7  # one of: SVM SVM-lin RF CART ADA LR NNN XGBoost CatBoost TabNet DNN XGBoost
CLF_BIN_WC2=$8  # one of: SVM SVM-lin RF CART ADA LR NNN XGBoost CatBoost TabNet DNN XGBoost
WEIGHT="${9:-0.5}"

if [ $PEPTIDE_TYPE == 'short' ] && [ $FEATURE_TYPE == 'all' ]
then
	FEATURES=$FEATURE_SHORT_ALL
	INPUT_FILE_TAG=$INPUT_FILE_TAG_SHORT
elif [ $PEPTIDE_TYPE == 'short' ] && [ $FEATURE_TYPE == 'old' ]
then
	FEATURES=$FEATURE_SHORT_ALL_OLD
	INPUT_FILE_TAG=$INPUT_FILE_TAG_SHORT
elif [ $PEPTIDE_TYPE == 'short' ] && [ $FEATURE_TYPE == 'sel' ]
then
	FEATURES=$FEATURE_SHORT_ALL_SEL
	INPUT_FILE_TAG=$INPUT_FILE_TAG_SHORT
elif [ $PEPTIDE_TYPE == 'short' ] && [ $FEATURE_TYPE == 'noMS' ]
then
	FEATURES=$FEATURE_SHORT_NO_IPMSDB
	INPUT_FILE_TAG=$INPUT_FILE_TAG_SHORT
elif [ $PEPTIDE_TYPE == 'short' ] && [ $FEATURE_TYPE == 'noINT' ]
then
	FEATURES=$FEATURE_SHORT_NO_INTOGEN
	INPUT_FILE_TAG=$INPUT_FILE_TAG_SHORT
elif [ $PEPTIDE_TYPE == 'short' ] && [ $FEATURE_TYPE == 'noMSINT' ]
then
	FEATURES=$FEATURE_SHORT_NO_IPMSDB_INTOGEN
	INPUT_FILE_TAG=$INPUT_FILE_TAG_SHORT
elif [ $PEPTIDE_TYPE == 'short' ] && [ $FEATURE_TYPE == 'set1' ]
then
	FEATURES=$FEATURE_SHORT_SET1
	INPUT_FILE_TAG=$INPUT_FILE_TAG_SHORT
elif [ $PEPTIDE_TYPE == 'short' ] && [ $FEATURE_TYPE == 'set2' ]
then
	FEATURES=$FEATURE_SHORT_SET2
	INPUT_FILE_TAG=$INPUT_FILE_TAG_SHORT
elif [ $PEPTIDE_TYPE == 'short' ] && [ $FEATURE_TYPE == 'set3' ]
then
	FEATURES=$FEATURE_SHORT_SET3
	INPUT_FILE_TAG=$INPUT_FILE_TAG_SHORT
elif [ $PEPTIDE_TYPE == 'short' ] && [ $FEATURE_TYPE == 'set4' ]
then
	FEATURES=$FEATURE_SHORT_SET4
	INPUT_FILE_TAG=$INPUT_FILE_TAG_SHORT
elif [ $PEPTIDE_TYPE == 'short' ] && [ $FEATURE_TYPE == 'set5' ]
then
	FEATURES=$FEATURE_SHORT_SET5
	INPUT_FILE_TAG=$INPUT_FILE_TAG_SHORT
elif [ $PEPTIDE_TYPE == 'short' ] && [ $FEATURE_TYPE == 'set6' ]
then
	FEATURES=$FEATURE_SHORT_SET6
	INPUT_FILE_TAG=$INPUT_FILE_TAG_SHORT
elif [ $PEPTIDE_TYPE == 'short' ] && [ $FEATURE_TYPE == 'set7' ]
then
	FEATURES=$FEATURE_SHORT_SET7
	INPUT_FILE_TAG=$INPUT_FILE_TAG_SHORT
elif [ $PEPTIDE_TYPE == 'short' ] && [ $FEATURE_TYPE == 'set8' ]
then
	FEATURES=$FEATURE_SHORT_SET8
	INPUT_FILE_TAG=$INPUT_FILE_TAG_SHORT
elif [ $PEPTIDE_TYPE == 'short' ] && [ $FEATURE_TYPE == 'set9' ]
then
	FEATURES=$FEATURE_SHORT_SET9
	INPUT_FILE_TAG=$INPUT_FILE_TAG_SHORT
elif [ $PEPTIDE_TYPE == 'short' ] && [ $FEATURE_TYPE == 'set10' ]
then
	FEATURES=$FEATURE_SHORT_SET10
	INPUT_FILE_TAG=$INPUT_FILE_TAG_SHORT
elif [ $PEPTIDE_TYPE == 'short' ] && [ $FEATURE_TYPE == 'set11' ]
then
	FEATURES=$FEATURE_SHORT_SET11
	INPUT_FILE_TAG=$INPUT_FILE_TAG_SHORT
elif [ $PEPTIDE_TYPE == 'short' ] && [ $FEATURE_TYPE == 'set12' ]
then
	FEATURES=$FEATURE_SHORT_SET12
	INPUT_FILE_TAG=$INPUT_FILE_TAG_SHORT
elif [ $PEPTIDE_TYPE == 'short' ] && [ $FEATURE_TYPE == 'set13' ]
then
	FEATURES=$FEATURE_SHORT_SET13
	INPUT_FILE_TAG=$INPUT_FILE_TAG_SHORT
elif [ $PEPTIDE_TYPE == 'short' ] && [ $FEATURE_TYPE == 'bind' ]
then
	FEATURES=$FEATURE_SHORT_BIND_SEL
	INPUT_FILE_TAG=$INPUT_FILE_TAG_SHORT
elif [ $PEPTIDE_TYPE == 'short' ] && [ $FEATURE_TYPE == 'mut' ]
then
	FEATURES=$FEATURE_SHORT_MUT_SEL
	INPUT_FILE_TAG=$INPUT_FILE_TAG_SHORT
elif [ $PEPTIDE_TYPE == 'long' ] && [ $FEATURE_TYPE == 'all' ]
then
	FEATURES=$FEATURE_LONG_ALL
	INPUT_FILE_TAG=$INPUT_FILE_TAG_LONG
	NR_NEGATIVE=-1
elif [ $PEPTIDE_TYPE == 'long' ] && [ $FEATURE_TYPE == 'sel' ]
then
	FEATURES=$FEATURE_LONG_ALL_SEL
	INPUT_FILE_TAG=$INPUT_FILE_TAG_LONG
	NR_NEGATIVE=-1
elif [ $PEPTIDE_TYPE == 'long' ] && [ $FEATURE_TYPE == 'mut' ]
then
	FEATURES=$FEATURE_LONG_MUT_SEL
	INPUT_FILE_TAG=$INPUT_FILE_TAG_LONG
	NR_NEGATIVE=-1
elif [ $PEPTIDE_TYPE == 'long' ] && [ $FEATURE_TYPE == 'noMS' ]
then
	FEATURES=$FEATURE_LONG_NO_IPMSDB
	INPUT_FILE_TAG=$INPUT_FILE_TAG_LONG
	NR_NEGATIVE=-1
elif [ $PEPTIDE_TYPE == 'long' ] && [ $FEATURE_TYPE == 'noINT' ]
then
	FEATURES=$FEATURE_LONG_NO_INTOGEN
	INPUT_FILE_TAG=$INPUT_FILE_TAG_LONG
	NR_NEGATIVE=-1
elif [ $PEPTIDE_TYPE == 'long' ] && [ $FEATURE_TYPE == 'noMSINT' ]
then
	FEATURES=$FEATURE_LONG_NO_IPMSDB_INTOGEN
	INPUT_FILE_TAG=$INPUT_FILE_TAG_LONG
	NR_NEGATIVE=-1
fi

#for CLF in SVM SVM-lin RF CART ADA LR NNN XGBoost CatBoost TabNet DNN XGBoost
if [ $ENCODING == 'float' ] 
then
	CAT_TO_NUM="-cat float"
elif [ $ENCODING == 'int' ]
then
	CAT_TO_NUM="-cat int"
else
	CAT_TO_NUM=""
fi	

cmd="PYTHONPATH=/home/localadmin/Priorization/python python3 Classifier/TestVotingClassifier.py -d $WORK_DIR -c1 $CLF_BIN_WC1 -c2 $CLF_BIN_WC2 -w $WEIGHT -s $SCORER -tr $TRAIN_SET -te $TEST_SET -i $INPUT_FILE_TAG -f $FEATURES -n $NORMALIZER -v 2 -a $ALPHA  -mt SNV -im CD8 CD4/CD8 $CAT_TO_NUM -pt $PEPTIDE_TYPE -eg $EXCL_GENES" 
echo $cmd
eval $cmd

